<?xml version="1.0" encoding="UTF-8" standalone="no"?><!--
  ~ Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
  ~
  ~ WSO2 Inc. licenses this file to you under the Apache License,
  ~ Version 2.0 (the "License"); you may not use this file except
  ~ in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  ~
  ~
  --><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.wso2</groupId>
        <artifactId>wso2</artifactId>
        <version>1.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.wso2.ei</groupId>
    <artifactId>integration-control-plane-parent</artifactId>
    <packaging>pom</packaging>
    <name>WSO2 Integration Control Plane - Parent</name>
    <version>1.2.0.5</version>

    <licenses>
        <license>
            <name>Apache License Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/wso2-support/integration-control-plane.git</url>
        <developerConnection>scm:git:https://github.com/wso2-support/integration-control-plane.git</developerConnection>
        <connection>scm:git:https://github.com/wso2-support/integration-control-plane.git</connection>
        
      <tag>v1.2.0.5</tag>
  </scm>

    <modules>
        <module>components</module>
        <module>distribution</module>
        <module>integration</module>
    </modules>

    <profiles>
        <profile>
            <id>sign</id>
            <activation>
                <property>
                    <name>sign</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>1.6</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>wso2-nexus</id>
            <name>WSO2 internal Repository</name>
            <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
                <checksumPolicy>ignore</checksumPolicy>
            </releases>
        </repository>
        <!--add the elasticsearch repo-->
        <repository>
            <id>elasticsearch-releases</id>
            <url>https://artifacts.elastic.co/maven</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>wso2.releases</id>
            <name>WSO2 internal Repository</name>
            <url>https://maven.wso2.org/nexus/content/repositories/releases/</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
                <checksumPolicy>ignore</checksumPolicy>
            </releases>
        </pluginRepository>
        <pluginRepository>
            <id>wso2.snapshots</id>
            <name>Apache Snapshot Repository</name>
            <url>https://maven.wso2.org/nexus/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </pluginRepository>
        <pluginRepository>
            <id>wso2-nexus</id>
            <name>WSO2 internal Repository</name>
            <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
                <checksumPolicy>ignore</checksumPolicy>
            </releases>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.wso2.ei</groupId>
                <artifactId>org.wso2.micro.integrator.dashboard.bootstrap</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.yaml/snakeyaml -->

            <dependency>
                <groupId>org.wso2.carbon.secvault</groupId>
                <artifactId>org.wso2.carbon.secvault.feature</artifactId>
                <version>${securevault.version}</version>
                <type>zip</type>
            </dependency>
            <dependency>
                <groupId>org.wso2.carbon.secvault</groupId>
                <artifactId>org.wso2.carbon.secvault.tools.feature</artifactId>
                <version>${securevault.version}</version>
                <type>zip</type>
            </dependency>
            <dependency>
                <groupId>org.wso2.carbon</groupId>
                <artifactId>org.wso2.carbon.securevault</artifactId>
                <version>${carbon.kernel.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>log4j</groupId>
                        <artifactId>log4j</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.wso2.securevault</groupId>
                <artifactId>org.wso2.securevault</artifactId>
                <version>${securevault.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>log4j</groupId>
                        <artifactId>log4j</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.jsoup</groupId>
                <artifactId>jsoup</artifactId>
                <version>${org.jsoup.version}</version>
            </dependency>

            <!-- Logging/SLF4J -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>${version.log4j.core}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>${version.log4j.core}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>${version.log4j.core}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-jcl</artifactId>
                <version>${version.log4j.core}</version>
            </dependency>

            <!-- Rest Api-->
            <dependency>
                <groupId>org.glassfish.jersey.containers</groupId>
                <artifactId>jersey-container-servlet-core</artifactId>
                <version>${glassfish.jersey.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey.inject</groupId>
                <artifactId>jersey-hk2</artifactId>
                <version>${glassfish.jersey.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey.media</groupId>
                <artifactId>jersey-media-json-binding</artifactId>
                <version>${glassfish.jersey.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>${javax.xml.bind.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.activation</groupId>
                <artifactId>activation</artifactId>
                <version>${javax.activation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${io.swagger.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${io.swagger.core.v3.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${jackson.core.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson.core.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson.core.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-yaml</artifactId>
                <version>${jackson.dataformat.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jdk8</artifactId>
                <version>${jackson.core.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-logging</groupId>
                <artifactId>commons-logging</artifactId>
                <version>${commons-logging.version}</version>
            </dependency>
            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>${h2.database.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons.lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>com.zaxxer</groupId>
                <artifactId>HikariCP</artifactId>
                <version>${hikari.cp.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
                <version>${httpcomponents.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${code.gson.version}</version>
            </dependency>
            <dependency>
                <groupId>org.wso2.config.mapper</groupId>
                <artifactId>config-mapper</artifactId>
                <version>${config.mapper.version}</version>
            </dependency>
            <dependency>
                <groupId>io.asgardeo.java.oidc.sdk</groupId>
                <artifactId>io.asgardeo.java.oidc.sdk</artifactId>
                <version>${asgardeo.java.oidc.sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>net.minidev</groupId>
                <artifactId>accessors-smart</artifactId>
                <version>${net.minidev.asm.version}</version>
            </dependency>
            <dependency>
                <groupId>net.minidev</groupId>
                <artifactId>json-smart</artifactId>
                <version>${net.minidev.json-smart.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.ws.commons.axiom.wso2</groupId>
                <artifactId>axiom</artifactId>
                <version>${axiom.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>${commons-codec.orbit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.wso2.ciphertool</groupId>
                <artifactId>org.wso2.ciphertool</artifactId>
                <version>${cipher.tool.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nimbusds</groupId>
                <artifactId>nimbus-jose-jwt</artifactId>
                <version>${nimbusds.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nimbusds</groupId>
                <artifactId>oauth2-oidc-sdk</artifactId>
                <version>${nimbusds.version}</version>
            </dependency>
            <dependency>
                <groupId>org.wso2.ei</groupId>
                <artifactId>org.wso2.micro.integrator.security</artifactId>
                <version>${mi.user.core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.wso2.ei</groupId>
                <artifactId>org.wso2.micro.integrator.core</artifactId>
                <version>${mi.user.core.version}</version>
            </dependency>
            
            <!-- Jetty Dependencies -->
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-server</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-servlet</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-webapp</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-util</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-http</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-io</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-security</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-xml</artifactId>
                <version>${jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.servlet</groupId>
                <artifactId>javax.servlet-api</artifactId>
                <version>3.1.0</version>
            </dependency>
            
            <!-- Other missing dependencies -->
            <dependency>
                <groupId>net.consensys.cava</groupId>
                <artifactId>cava-toml</artifactId>
                <version>${cava.toml.version}</version>
            </dependency>
            <dependency>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-runtime</artifactId>
                <version>${antlr4.runtime.version}</version>
            </dependency>
               <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jdk8</artifactId>
                <version>${fasterxml.jackson.datatype.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hubspot.immutables</groupId>
                <artifactId>immutables-exceptions</artifactId>
                <version>${com.hubspot.immutables.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.validation</groupId>
                <artifactId>validation-api</artifactId>
                <version>${javax.validation.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>${maven.exec.plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <configuration>
                    <preparationGoals>clean install</preparationGoals>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven.javadoc.plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <!--This parameter disables doclint-->
                            <doclint>none</doclint>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <source>1.8</source>
                    <attach>true</attach>
                    <additionalJOption>-Xdoclint:none</additionalJOption>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <properties>
        <carbon.p2.plugin.version>5.1.2</carbon.p2.plugin.version>
        <maven.resources.plugin.version>3.1.0</maven.resources.plugin.version>
        <maven.antrun.plugin.version>1.8</maven.antrun.plugin.version>
        <maven.surefire.plugin.version>2.22.2</maven.surefire.plugin.version>
        <!--<jacoco.maven.plugin.version>0.8.2</jacoco.maven.plugin.version>-->
        <!--<testng.version>6.11</testng.version>-->
        <maven.dependency.plugin.version>3.1.1</maven.dependency.plugin.version>
        <docker.maven.plugin.version>1.0.0</docker.maven.plugin.version>
        <org.snakeyml.version>1.26</org.snakeyml.version>
        <maven.jar.plugin.version>3.0.2</maven.jar.plugin.version>
        <version.jaxb.api>2.4.0-b180830.0359</version.jaxb.api>
        <verion.javax.annotation.annotation-api>1.3.2</verion.javax.annotation.annotation-api>
        <maven.checkstyle.plugin.version>3.0.0</maven.checkstyle.plugin.version>

        <securevault.version>1.1.2</securevault.version>
        <carbon.kernel.version>4.8.1</carbon.kernel.version>
        <org.jsoup.version>1.15.3</org.jsoup.version>

        <!-- Logging/SLF4J -->
        <slf4j.version>1.7.36</slf4j.version>
        <version.log4j.core>2.17.2</version.log4j.core>

        <!-- Maven-->
        <carbon.feature.plugin.version>3.1.3</carbon.feature.plugin.version>
        <maven.findbugsplugin.version.exclude>findbugs-exclude.xml</maven.findbugsplugin.version.exclude>
        <maven.clean.plugin.version>3.0.0</maven.clean.plugin.version>
        <maven.exec.plugin.version>1.5.0</maven.exec.plugin.version>
        <maven.javadoc.plugin.version>3.4.1</maven.javadoc.plugin.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Rest api -->
        <glassfish.jersey.version>2.26</glassfish.jersey.version>
        <javax.xml.bind.version>2.3.0</javax.xml.bind.version>
        <javax.activation.version>1.1</javax.activation.version>
        <io.swagger.version>1.6.5</io.swagger.version>
        <io.swagger.core.v3.version>2.1.12</io.swagger.core.v3.version>
        <jackson.core.version>2.15.0</jackson.core.version>
        <jackson.dataformat.version>${jackson.core.version}</jackson.dataformat.version>
        <commons-logging.version>1.2</commons-logging.version>
        <commons.lang3.version>3.18.0</commons.lang3.version>
        <commons-codec.orbit.version>1.15</commons-codec.orbit.version>
        <hikari.cp.version>3.4.5</hikari.cp.version>
        <httpcomponents.version>4.5.13</httpcomponents.version>
        <code.gson.version>2.11.0</code.gson.version>
        <config.mapper.version>1.0.26</config.mapper.version>
        <asgardeo.java.oidc.sdk.version>0.1.27</asgardeo.java.oidc.sdk.version>
        <net.minidev.asm.version>2.4.8</net.minidev.asm.version>
        <net.minidev.json-smart.version>2.5.2</net.minidev.json-smart.version>
        <guava.version>33.2.0-jre</guava.version>
        <nimbusds.version>9.39.1</nimbusds.version>
        <axiom.version>1.2.11-wso2v17</axiom.version>
        <cipher.tool.version>1.1.24</cipher.tool.version>
        <maven.war.plugin.version>3.3.2</maven.war.plugin.version>
        <mi.user.core.version>4.2.0</mi.user.core.version>
        <com.hubspot.immutables.version>1.11.2</com.hubspot.immutables.version>
        <javax.validation.version>2.0.1.Final</javax.validation.version>
        
        <!-- Jetty -->
        <jetty.version>9.4.58.v20250814</jetty.version>
        
        <!-- Other missing dependencies -->
        <cava.toml.version>0.5.0</cava.toml.version>
        <antlr4.runtime.version>4.7.2</antlr4.runtime.version>
        
        <!-- Maven plugins -->
        <maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
    <project.scm.id>wso2-scm-server</project.scm.id></properties>
</project>